name: CI

on: push

env:
  COLUMNS: 120

jobs:
  ruff-format:
    name: ruff format
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@local-actions
    with:
      cmd: poetry run ruff format dsk -- --check

  ruff-lint:
    name: ruff lint
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@local-actions
    with:
      cmd: poetry run ruff dsk

  mypy:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@local-actions
    with:
      cmd: poetry run mypy dsk

  lockfile-consistency:
    name: lockfile consistency
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@local-actions
    with:
      cmd: poetry lock --check

  unused-dependencies:
    name: unused dependencies
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@local-actions
    with:
      cmd: poetry run deptry dsk

  python-missing-init:
    name: missing __init__.py files
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: check for missing __init__.py files
        uses: ljodal/python-actions/check-for-missing-init@feature/check-for-missing-init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: dsk

  ci-done:
    # Gather job which deploy workflow can wait on.
    name: CI done
    needs:
      - ruff-format
      - ruff-lint
      - mypy
      - lockfile-consistency
      - unused-dependencies
      - python-missing-init
    runs-on: ubuntu-20.04
    steps:
      - run: echo "CI done!"
